name: blog_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^8.2.1
  cached_network_image: ^4.0.2
  dio: ^5.11.1
  flutter_riverpod: ^3.4.3
  intl: ^0.20.2
  shimmer: ^4.0.0
  webview_flutter: ^4.14.1
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.5
  image_picker: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Chap
      fonts:
        - asset: assets/fonts/ChapTrial-Light.otf
          weight: 300
        - asset: assets/fonts/ChapTrial-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/ChapTrial-Regular.otf
          weight: 400
        - asset: assets/fonts/ChapTrial-RegularItalic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/ChapTrial-Medium.otf
          weight: 500
        - asset: assets/fonts/ChapTrial-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/ChapTrial-Semibold.otf
          weight: 600
        - asset: assets/fonts/ChapTrial-SemiboldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/ChapTrial-Bold.otf
          weight: 700
        - asset: assets/fonts/ChapTrial-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/ChapTrial-Black.otf
          weight: 900
        - asset: assets/fonts/ChapTrial-BlackItalic.otf
          weight: 900
          style: italic
